"""
================================================================
CONTRACT  :  CodeEditor
MODULE    :  backend/utilities/code_editor
VERSION   :  1.0.0   |   Sprint 1
================================================================

WHERE THIS SITS IN JINIE
-------------------------
CodeEditor sits between FileHandler and MdConverter.

  FileHandler.read(dart_file)
          │  FilePayload
          ▼
  CodeEditor.load_file(payload)
  CodeEditor.insert_lines(...)   ← add import statements, widget blocks
  CodeEditor.replace_token(...)  ← rename class names, swap placeholders
  CodeEditor.delete_lines(...)   ← remove scaffolding comments
  CodeEditor.get_payload()
          │  CodePayload
          ▼
  MdConverter.convert(payload)  ← converts Dart code to Markdown
                                   for the SRS document or live preview

REAL JINIE USAGE
-----------------
When CodeT5 generates a Dart widget file, the Compiler calls:
  1. FileHandler.write(path, raw_dart_code)
  2. FileHandler.read(path)               → FilePayload
  3. CodeEditor.load_file(payload)
       .insert_lines(0, ["// Generated by Jinie v1.0"])
       .replace_token("__APP_NAME__", "ZaraStore")
       .replace_token("__PRIMARY_COLOR__", "Color(0xFF1A73E8)")
       .get_payload()                     → CodePayload
  4. MdConverter.convert(code_payload)   → shown in SRS Viewer (Module 13)

WHAT CodeEditor GUARANTEES
---------------------------
load_file(payload)
    → self   (resets edit history; fluent API)

insert_lines(after_line, lines)
    → self   inserts lines after after_line (1-based); 0 = prepend

replace_block(start_line, end_line, new_content)
    → self   replaces lines start..end with new_content

delete_lines(start_line, end_line)
    → self   removes lines start..end inclusive

replace_token(old_token, new_token, occurrence=-1)
    → self   occurrence=-1 replaces ALL; N replaces only the Nth

get_payload()
    → CodePayload
        .edited_content   str  full Dart/py text after all edits
                               ← THIS is what MdConverter receives
        .original_content str  unchanged original from FilePayload
        .language         str  "dart" / "python" / "json" etc
        .extension        str  ".dart" / ".py" etc
        .source_path      str  absolute path of the source file
        .edit_history     list[EditReceipt]  every edit in order
        .trace_id         str  "CE-<uuid4>"
        .source_trace_id  str  FilePayload.trace_id  ← traceability chain

last_receipt  (property)
    → EditReceipt from most recent edit

CONTRACT RULES
--------------
PRE  (caller must guarantee)
  1. load_file() always receives a FilePayload — never a raw string
  2. Line numbers are 1-based
  3. new_content is always str, never None
  4. CodeEditor is purely in-memory — it never writes to disk
     The Compiler/Reformatter persists edits via FileHandler.write()

POST (CodeEditor guarantees)
  1. Edits applied in the order called
  2. get_payload() is idempotent — safe to call multiple times
  3. original_content is never modified regardless of edits
  4. trace_id always UUID4 prefixed "CE-"

ERROR CODES
-----------
  NO_FILE_LOADED     any edit called before load_file()
  LINE_OUT_OF_RANGE  line number outside valid range
  EMPTY_CONTENT      new_content is empty string where not allowed
  TOKEN_NOT_FOUND    old_token absent, or Nth occurrence missing

DOWNSTREAM CONTRACT  (what MdConverter.convert expects)
  MdConverter uses from CodePayload:
    .edited_content  → the Dart code text to wrap in fenced code block
    .language        → "dart" for ```dart  fenced block tag
    .source_path     → attribution comment in the Markdown
    .trace_id        → chained into Traceability Matrix (Module 03)

AGILE ROADMAP
  Sprint 1  load_file, insert_lines, delete_lines, replace_token,
            replace_block, get_payload
  Sprint 2  unified diff generation, multi-file session, undo stack
================================================================
"""

from dataclasses import dataclass


# ── data types ────────────────────────────────────────────────────────────────

@dataclass
class EditReceipt:
    """
    Produced by every mutating CodeEditor operation.
    Stored in CodePayload.edit_history and accessible via last_receipt.
    """
    operation:           str   # INSERT | DELETE | REPLACE_BLOCK | REPLACE_TOKEN
    line_start:          int   # first affected line (1-based); 0 for token ops
    line_end:            int   # last affected line  (1-based); 0 for token ops
    replacements:        int   # count of substitutions (for REPLACE_TOKEN)
    trace_id:            str   # "CE-<uuid4>" — unique per edit
    snapshot_line_count: int   # total lines AFTER this edit


@dataclass
class CodePayload:
    """
    Output of CodeEditor.get_payload().
    Direct input of MdConverter.convert().

    Treat as immutable after get_payload() returns.
    """
    edited_content:   str   # Dart/py text after edits — MdConverter input
    original_content: str   # unchanged original from FilePayload
    language:         str   # "dart" | "python" | "json" | "yaml" | "markdown"
    extension:        str   # ".dart" | ".py" etc
    source_path:      str   # absolute path of the source file
    edit_history:     list  # list[EditReceipt] in call order
    trace_id:         str   # "CE-<uuid4>" — session ID
    source_trace_id:  str   # FilePayload.trace_id → traceability chain


# ── error type ────────────────────────────────────────────────────────────────

class CodeEditorError(Exception):
    """
    Raised by CodeEditor for every contract violation.

    Usage:
        except CodeEditorError as e:
            if e.code == "TOKEN_NOT_FOUND":
                ...
    """
    CODES = frozenset({
        "NO_FILE_LOADED",
        "LINE_OUT_OF_RANGE",
        "EMPTY_CONTENT",
        "TOKEN_NOT_FOUND",
    })

    def __init__(self, code: str, message: str) -> None:
        if code not in self.CODES:
            raise ValueError(f"Unknown CodeEditorError code: {code!r}")
        self.code = code
        super().__init__(f"[CodeEditor/{code}] {message}")


# ── abstract interface ────────────────────────────────────────────────────────

class ICodeEditor:
    """
    Abstract contract.
    Compiler and Reformatter import ICodeEditor, not the concrete class.
    """

    def load_file(self, payload) -> "ICodeEditor":
        """
        Load a FilePayload produced by FileHandler.read().

        PRE  payload is a FilePayload instance, not a raw string
        POST internal state initialised; edit history cleared; returns self
        ERR  TypeError if wrong type passed
        """
        raise NotImplementedError

    def insert_lines(self, after_line: int,
                     lines: list) -> "ICodeEditor":
        """
        Insert lines after after_line (1-based). 0 = prepend.

        In Jinie used for:
          • Adding  // Generated by Jinie  header comment
          • Inserting import statements at top of Dart file
          • Adding a new widget method block inside a class

        PRE  load_file() called; 0 <= after_line <= total_lines
        POST lines inserted; EditReceipt recorded; returns self
        ERR  CodeEditorError(LINE_OUT_OF_RANGE | NO_FILE_LOADED)
        """
        raise NotImplementedError

    def replace_block(self, start_line: int, end_line: int,
                      new_content: str) -> "ICodeEditor":
        """
        Replace lines [start_line, end_line] with new_content.

        In Jinie used for:
          • Replacing a placeholder widget block with generated code

        PRE  load_file() called; 1 <= start <= end <= total
        POST block replaced; EditReceipt recorded; returns self
        ERR  CodeEditorError(LINE_OUT_OF_RANGE | NO_FILE_LOADED)
        """
        raise NotImplementedError

    def delete_lines(self, start_line: int,
                     end_line: int) -> "ICodeEditor":
        """
        Delete lines [start_line, end_line] inclusive.

        In Jinie used for:
          • Removing scaffolding TODO comments from generated Dart files

        PRE  load_file() called; 1 <= start <= end <= total
        POST lines removed; EditReceipt recorded; returns self
        ERR  CodeEditorError(LINE_OUT_OF_RANGE | NO_FILE_LOADED)
        """
        raise NotImplementedError

    def replace_token(self, old_token: str, new_token: str,
                      occurrence: int = -1) -> "ICodeEditor":
        """
        Replace occurrences of old_token with new_token.
        occurrence = -1  → replace ALL
        occurrence = N   → replace only the Nth (1-based)

        In Jinie used for:
          • Replacing __APP_NAME__ with actual business name
          • Replacing __PRIMARY_COLOR__ with user's chosen hex color
          • Renaming placeholder class names after CodeT5 generation

        PRE  load_file() called; old_token non-empty
        POST replacements applied; EditReceipt recorded; returns self
        ERR  CodeEditorError(TOKEN_NOT_FOUND | NO_FILE_LOADED)
        """
        raise NotImplementedError

    def get_payload(self) -> CodePayload:
        """
        Return CodePayload after all edits.

        PRE  load_file() has been called
        POST CodePayload returned; history not reset; idempotent
             CodePayload.edited_content is the exact string
             MdConverter.convert() will receive
        ERR  CodeEditorError(NO_FILE_LOADED)
        """
        raise NotImplementedError