"""
backend/utilities/code_editor/code_editor.py
=============================================
Concrete implementation of ICodeEditor for the Jinie project.

Sprint 1  :  load_file, insert_lines, delete_lines, replace_token,
             replace_block, get_payload
Sprint 2  :  unified diff, multi-file session, undo stack

Where this sits in the Jinie pipeline
--------------------------------------
  FileHandler.read(path)
          │  FilePayload
          ▼
  CodeEditor.load_file(payload)
  CodeEditor.insert_lines(0, ["// Generated by Jinie"])
  CodeEditor.replace_token("__APP_NAME__", "ZaraStore")
  CodeEditor.get_payload()
          │  CodePayload
          ▼
  MdConverter.convert(payload)  ← next submodule

Real example from Jinie Compiler (Module 06)
---------------------------------------------
  # After CodeT5 generates a product card widget:
  fh = FileHandler()
  fh.write("/project/lib/widgets/product_card.dart", codet5_output)

  payload = (
      CodeEditor()
      .load_file(fh.read("/project/lib/widgets/product_card.dart"))
      .insert_lines(0, ["// Generated by Jinie — do not edit manually"])
      .replace_token("__APP_NAME__",      "ZaraStore")
      .replace_token("__PRIMARY_COLOR__", "Color(0xFF1A73E8)")
      .replace_token("__CURRENCY__",      "PKR")
      .get_payload()
  )
  # payload.edited_content  → clean Dart code ready for MdConverter
"""

import uuid
from copy import deepcopy

from backend.utilities.file_handler.file_handler_contract import FilePayload
from backend.utilities.code_editor.code_editor_contract import (
    ICodeEditor,
    CodePayload,
    EditReceipt,
    CodeEditorError,
)


# ── language detection ────────────────────────────────────────────────────────
# Maps file extension to language tag used by MdConverter for fenced blocks

_LANG_MAP: dict[str, str] = {
    ".dart":  "dart",        # Flutter widget files — main target
    ".py":    "python",      # Backend Flask/FastAPI files
    ".json":  "json",        # pubspec.yaml companion, firebase.json
    ".yaml":  "yaml",        # pubspec.yaml
    ".yml":   "yaml",
    ".md":    "markdown",    # SRS documents
    ".js":    "javascript",  # React frontend files
    ".ts":    "typescript",
    ".jsx":   "jsx",
    ".tsx":   "tsx",
    ".html":  "html",
    ".css":   "css",
    ".env":   "bash",
    ".toml":  "toml",
    ".xml":   "xml",
    ".txt":   "text",
}


def _detect_lang(ext: str) -> str:
    return _LANG_MAP.get(ext.lower(), "text")


def _make_trace_id() -> str:
    return f"CE-{uuid.uuid4()}"


# ── implementation ────────────────────────────────────────────────────────────

class CodeEditor(ICodeEditor):
    """
    Applies in-memory edits to generated Flutter/Dart files.

    Fluent API — every edit returns self so calls chain:

        code_payload = (
            CodeEditor()
            .load_file(file_payload)
            .insert_lines(0, ["// Generated by Jinie"])
            .replace_token("__APP_NAME__", "ZaraStore")
            .replace_token("__CURRENCY__", "PKR")
            .get_payload()   ← CodePayload ready for MdConverter
        )
    """

    def __init__(self) -> None:
        self._lines:        list[str]          = []
        self._original:     str                = ""
        self._fp:           FilePayload | None = None   # loaded FilePayload
        self._history:      list[EditReceipt]  = []
        self._session_tid:  str                = _make_trace_id()
        self._last_receipt: EditReceipt | None = None

    # ── properties ────────────────────────────────────────────────────────────

    @property
    def last_receipt(self) -> EditReceipt | None:
        """EditReceipt from the most recent edit; None before any edit."""
        return self._last_receipt

    @property
    def line_count(self) -> int:
        """Current number of lines in the working copy."""
        self._need_file()
        return len(self._lines)

    # ── guards ────────────────────────────────────────────────────────────────

    def _need_file(self) -> None:
        if self._fp is None:
            raise CodeEditorError(
                "NO_FILE_LOADED",
                "Call load_file(payload) before any operation. "
                "Pass the FilePayload returned by FileHandler.read().",
            )

    def _check_range(self, start: int, end: int) -> None:
        total = len(self._lines)
        if start < 1 or end > total or start > end:
            raise CodeEditorError(
                "LINE_OUT_OF_RANGE",
                f"Lines {start}–{end} are out of range. "
                f"File currently has {total} lines.",
            )

    def _record(self, receipt: EditReceipt) -> None:
        self._history.append(receipt)
        self._last_receipt = receipt

    # ── load_file ─────────────────────────────────────────────────────────────

    def load_file(self, payload: FilePayload) -> "CodeEditor":
        """
        Load a FilePayload produced by FileHandler.read().

        Resets all edit history — each new file is a fresh session.
        Returns self so you can chain immediately:
            ce.load_file(fp).insert_lines(0, ["// header"])
        """
        if not isinstance(payload, FilePayload):
            raise TypeError(
                f"load_file() requires a FilePayload, got "
                f"{type(payload).__name__!r}. "
                "Always pass FileHandler.read() output directly here."
            )

        self._fp           = payload
        self._original     = payload.raw_content
        self._lines        = payload.raw_content.splitlines()
        self._history      = []
        self._session_tid  = _make_trace_id()
        self._last_receipt = None
        return self

    # ── insert_lines ──────────────────────────────────────────────────────────

    def insert_lines(self, after_line: int,
                     lines: list[str]) -> "CodeEditor":
        """
        Insert lines after after_line (1-based).
        after_line = 0  → prepend before line 1.

        Jinie example:
            # Add generated-by header at the very top of a Dart file
            ce.insert_lines(0, ["// Generated by Jinie — do not edit"])
        """
        self._need_file()
        total = len(self._lines)

        if after_line < 0 or after_line > total:
            raise CodeEditorError(
                "LINE_OUT_OF_RANGE",
                f"after_line={after_line} is out of range [0, {total}].",
            )

        for i, line in enumerate(lines):
            self._lines.insert(after_line + i, line)

        self._record(EditReceipt(
            operation           = "INSERT",
            line_start          = after_line + 1,
            line_end            = after_line + len(lines),
            replacements        = 0,
            trace_id            = _make_trace_id(),
            snapshot_line_count = len(self._lines),
        ))
        return self

    # ── replace_block ─────────────────────────────────────────────────────────

    def replace_block(self, start_line: int, end_line: int,
                      new_content: str) -> "CodeEditor":
        """
        Replace lines [start_line, end_line] inclusive with new_content.

        Jinie example:
            # Replace a placeholder build() method with CodeT5 output
            ce.replace_block(10, 18, codet5_generated_build_method)
        """
        self._need_file()
        self._check_range(start_line, end_line)

        new_lines = new_content.splitlines()
        self._lines[start_line - 1 : end_line] = new_lines

        self._record(EditReceipt(
            operation           = "REPLACE_BLOCK",
            line_start          = start_line,
            line_end            = start_line + len(new_lines) - 1,
            replacements        = 1,
            trace_id            = _make_trace_id(),
            snapshot_line_count = len(self._lines),
        ))
        return self

    # ── delete_lines ──────────────────────────────────────────────────────────

    def delete_lines(self, start_line: int,
                     end_line: int) -> "CodeEditor":
        """
        Delete lines [start_line, end_line] inclusive.

        Jinie example:
            # Remove TODO scaffolding comments after code is finalised
            ce.delete_lines(3, 5)
        """
        self._need_file()
        self._check_range(start_line, end_line)

        del self._lines[start_line - 1 : end_line]

        self._record(EditReceipt(
            operation           = "DELETE",
            line_start          = start_line,
            line_end            = end_line,
            replacements        = 0,
            trace_id            = _make_trace_id(),
            snapshot_line_count = len(self._lines),
        ))
        return self

    # ── replace_token ─────────────────────────────────────────────────────────

    def replace_token(self, old_token: str, new_token: str,
                      occurrence: int = -1) -> "CodeEditor":
        """
        Replace occurrences of old_token with new_token.
        occurrence = -1  → replace ALL
        occurrence = N   → replace only the Nth (1-based)

        Jinie examples:
            ce.replace_token("__APP_NAME__",      "ZaraStore")
            ce.replace_token("__PRIMARY_COLOR__", "Color(0xFF1A73E8)")
            ce.replace_token("__CURRENCY__",      "PKR")
            ce.replace_token("MyWidget",          "ProductCard")
        """
        self._need_file()

        text = "\n".join(self._lines)

        if old_token not in text:
            raise CodeEditorError(
                "TOKEN_NOT_FOUND",
                f"Token {old_token!r} was not found in the current content. "
                f"Check the Dart file for the correct placeholder name.",
            )

        count = text.count(old_token)

        if occurrence == -1:
            new_text = text.replace(old_token, new_token)
            replaced = count
        else:
            if occurrence < 1 or occurrence > count:
                raise CodeEditorError(
                    "TOKEN_NOT_FOUND",
                    f"Occurrence {occurrence} of {old_token!r} does not exist. "
                    f"Token appears {count} time(s) total.",
                )
            idx = -1
            for _ in range(occurrence):
                idx = text.find(old_token, idx + 1)
            new_text = text[:idx] + new_token + text[idx + len(old_token):]
            replaced = 1

        self._lines = new_text.splitlines()

        self._record(EditReceipt(
            operation           = "REPLACE_TOKEN",
            line_start          = 0,
            line_end            = 0,
            replacements        = replaced,
            trace_id            = _make_trace_id(),
            snapshot_line_count = len(self._lines),
        ))
        return self

    # ── get_payload ───────────────────────────────────────────────────────────

    def get_payload(self) -> CodePayload:
        """
        Return CodePayload after all edits.

        CodePayload.edited_content is the exact Dart/Python text string
        that MdConverter.convert() receives as its input.

        Idempotent — safe to call multiple times.
        """
        self._need_file()

        return CodePayload(
            edited_content   = "\n".join(self._lines),
            original_content = self._original,
            language         = _detect_lang(self._fp.extension),
            extension        = self._fp.extension,
            source_path      = self._fp.path,
            edit_history     = deepcopy(self._history),
            trace_id         = self._session_tid,
            source_trace_id  = self._fp.trace_id,
        )

    # ── preview ───────────────────────────────────────────────────────────────

    def preview(self, start_line: int = 1,
                end_line: int | None = None) -> str:
        """
        Return a slice of the working copy as a string.
        Does not affect edit history or payload — read-only inspection.
        """
        self._need_file()
        end = end_line if end_line is not None else len(self._lines)
        return "\n".join(self._lines[start_line - 1 : end])