import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {View,Text} from 'react-native';
import App from './App';
import config from './src/config.json';
import ProductCard from './src/components/ProductCard';
import HeroBanner from './src/components/HeroBanner';
import CategoryChip from './src/components/CategoryChip';
import SearchBar from './src/components/SearchBar';
import CartItem from './src/components/CartItem';
import CheckoutButton from './src/components/CheckoutButton';
import PriceTag from './src/components/PriceTag';
import DiscountBadge from './src/components/DiscountBadge';
import RatingStars from './src/components/RatingStars';
import SectionHeading from './src/components/SectionHeading';
import EmptyState from './src/components/EmptyState';
import ContactCard from './src/components/ContactCard';
import AboutCard from './src/components/AboutCard';
import QuantityControl from './src/components/QuantityControl';
import OrderSummary from './src/components/OrderSummary';
import AddressField from './src/components/AddressField';
import NavigationTab from './src/components/NavigationTab';
import StockBadge from './src/components/StockBadge';
import ServiceCard from './src/components/ServiceCard';
import Divider from './src/components/Divider';
const components={ProductCard,HeroBanner,CategoryChip,SearchBar,CartItem,CheckoutButton,PriceTag,DiscountBadge,RatingStars,SectionHeading,EmptyState,ContactCard,AboutCard,QuantityControl,OrderSummary,AddressField,NavigationTab,StockBadge,ServiceCard,Divider};
function Gallery(){const [value,setValue]=useState('');const [quantity,setQuantity]=useState(1);const [message,setMessage]=useState('');const C=components[new URLSearchParams(location.search).get('component')];return C?<View style={{padding:24,gap:24,backgroundColor:'#fff',minHeight:'100%'}}><Text style={{fontSize:12,color:'#888'}}>ISOLATED COMPONENT PREVIEW</Text><C product={config.products[0]} primary={config.primary} value={C===QuantityControl?quantity:value} onChange={setQuantity} onChangeText={setValue} quantity={quantity} onIncrease={()=>setQuantity(q=>q+1)} onDecrease={()=>setQuantity(q=>Math.max(0,q-1))} onOpen={()=>setMessage('Open product callback fired')} onAdd={()=>setMessage('Add to cart callback fired')} onPress={()=>setMessage('Press callback fired')} onBook={()=>setMessage('Booking callback fired')} onAction={()=>setMessage('Action callback fired')}/><Text>{message}</Text></View>:<App/>;}
createRoot(document.getElementById('root')).render(<Gallery/>);
document.addEventListener('click',e=>{if(e.altKey){e.preventDefault();e.stopPropagation();const el=document.querySelector('[id^=jinie-page-]');parent.postMessage({type:'jinie-annotation',page:el?.id.replace('jinie-page-',''),text:e.target.textContent?.slice(0,100)},'*');}},true);
