"""
srs_document_generator.py

Converts srs_output.json (the FullSRSOutput dumped by run_srs_pipeline)
into a polished, professionally formatted Word document — a proper
Software Requirements Specification document, not just raw JSON.

Usage:
    python srs_document_generator.py srs_output.json SRS_Document.docx

Requires: pip install python-docx
"""

from __future__ import annotations

import json
import sys
from datetime import datetime

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ---------------------------------------------------------------------
# Brand palette
# ---------------------------------------------------------------------
NAVY = RGBColor(0x0B, 0x1F, 0x3A)
GOLD = RGBColor(0xC9, 0xA2, 0x27)
LIGHT_GOLD_BG = "F5EBCF"
LIGHT_NAVY_BG = "1B3A5C"
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)


def _set_cell_background(cell, hex_color: str) -> None:
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), hex_color)
    cell._tc.get_or_add_tcPr().append(shading)


def _set_cell_text(cell, text: str, bold: bool = False, color: RGBColor = None, size: int = 10) -> None:
    cell.text = ""
    p = cell.paragraphs[0]
    run = p.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)
    if color:
        run.font.color.rgb = color


def _add_heading(doc: Document, text: str, level: int = 1) -> None:
    heading = doc.add_heading(text, level=level)
    for run in heading.runs:
        run.font.color.rgb = NAVY
    if level == 1:
        heading.paragraph_format.space_before = Pt(24)
        heading.paragraph_format.space_after = Pt(12)


def _add_cover_page(doc: Document, app_prompt: str, generated_at: str, trace_id: str) -> None:
    for _ in range(6):
        doc.add_paragraph()

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("SOFTWARE REQUIREMENTS")
    run.font.size = Pt(34)
    run.font.bold = True
    run.font.color.rgb = NAVY

    title2 = doc.add_paragraph()
    title2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run2 = title2.add_run("SPECIFICATION")
    run2.font.size = Pt(34)
    run2.font.bold = True
    run2.font.color.rgb = GOLD

    doc.add_paragraph()

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run("Generated by the Jinie SRS Pipeline")
    sub_run.font.size = Pt(14)
    sub_run.font.italic = True
    sub_run.font.color.rgb = DARK_GRAY

    for _ in range(8):
        doc.add_paragraph()

    meta_table = doc.add_table(rows=3, cols=2)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta_table.columns[0].width = Inches(1.8)
    meta_table.columns[1].width = Inches(4.2)

    rows = [
        ("App Description:", app_prompt),
        ("Generated:", generated_at),
        ("Trace ID:", trace_id),
    ]
    for i, (label, value) in enumerate(rows):
        _set_cell_text(meta_table.rows[i].cells[0], label, bold=True, color=NAVY, size=11)
        _set_cell_text(meta_table.rows[i].cells[1], value, size=11)

    doc.add_page_break()


def _add_table_of_contents_summary(doc: Document, srs: dict) -> None:
    _add_heading(doc, "Document Overview", level=1)
    p = doc.add_paragraph()
    p.add_run(
        f"This document was automatically generated from a natural-language app description "
        f"and contains {len(srs['functional_requirements']['requirements'])} functional requirements, "
        f"{len(srs['non_functional_requirements']['requirements'])} non-functional requirements, "
        f"{len(srs['sitemap']['nodes'])} application screens, and "
        f"{len(srs['entities']['entities'])} data entities."
    )
    doc.add_paragraph()


def _add_functional_requirements(doc: Document, frs: list) -> None:
    _add_heading(doc, "1. Functional Requirements", level=1)

    table = doc.add_table(rows=1, cols=5)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    widths = [Inches(0.7), Inches(2.6), Inches(1.1), Inches(1.4), Inches(0.9)]
    headers = ["ID", "Description", "Priority", "Actors", "Inputs"]

    for i, cell in enumerate(table.rows[0].cells):
        cell.width = widths[i]
        _set_cell_text(cell, headers[i], bold=True, color=WHITE, size=10)
        _set_cell_background(cell, LIGHT_NAVY_BG)

    for fr in frs:
        row = table.add_row().cells
        for i, w in enumerate(widths):
            row[i].width = w
        _set_cell_text(row[0], fr["fr_id"], bold=True, size=9)
        _set_cell_text(row[1], fr["description"], size=9)
        _set_cell_text(row[2], fr["priority"].upper(), size=9)
        _set_cell_text(row[3], ", ".join(fr["actors"]), size=9)
        _set_cell_text(row[4], ", ".join(fr["inputs"]) or "—", size=9)

    doc.add_paragraph()


def _add_non_functional_requirements(doc: Document, nfrs: list) -> None:
    _add_heading(doc, "2. Non-Functional Requirements", level=1)

    table = doc.add_table(rows=1, cols=4)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    widths = [Inches(0.8), Inches(1.3), Inches(3.0), Inches(1.6)]
    headers = ["ID", "Category", "Constraint", "Linked FR"]

    for i, cell in enumerate(table.rows[0].cells):
        cell.width = widths[i]
        _set_cell_text(cell, headers[i], bold=True, color=WHITE, size=10)
        _set_cell_background(cell, LIGHT_NAVY_BG)

    for nfr in nfrs:
        row = table.add_row().cells
        for i, w in enumerate(widths):
            row[i].width = w
        _set_cell_text(row[0], nfr["nfr_id"], bold=True, size=9)
        _set_cell_text(row[1], nfr["category"].capitalize(), size=9)
        constraint_text = nfr["constraint"]
        if nfr.get("threshold_value") is not None:
            constraint_text += f" ({nfr['threshold_value']}{nfr.get('threshold_unit', '')})"
        _set_cell_text(row[2], constraint_text, size=9)
        _set_cell_text(row[3], nfr.get("linked_fr_id") or "Global", size=9)

    doc.add_paragraph()


def _add_sitemap(doc: Document, sitemap: dict) -> None:
    _add_heading(doc, "3. Application Sitemap", level=1)

    table = doc.add_table(rows=1, cols=4)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    widths = [Inches(1.8), Inches(1.3), Inches(1.3), Inches(2.1)]
    headers = ["Screen Name", "Route", "Type", "Entry Point"]

    for i, cell in enumerate(table.rows[0].cells):
        cell.width = widths[i]
        _set_cell_text(cell, headers[i], bold=True, color=WHITE, size=10)
        _set_cell_background(cell, LIGHT_NAVY_BG)

    for node in sitemap["nodes"]:
        row = table.add_row().cells
        for i, w in enumerate(widths):
            row[i].width = w
        _set_cell_text(row[0], node["screen_name"], bold=True, size=9)
        _set_cell_text(row[1], node["route"], size=9)
        _set_cell_text(row[2], node["screen_type"].capitalize(), size=9)
        _set_cell_text(row[3], "Yes" if node["is_entry_point"] else "No", size=9)

    if sitemap["edges"]:
        doc.add_paragraph()
        nav_heading = doc.add_paragraph()
        nav_run = nav_heading.add_run("Navigation Flow")
        nav_run.bold = True
        nav_run.font.color.rgb = NAVY

        screen_lookup = {n["screen_id"]: n["screen_name"] for n in sitemap["nodes"]}
        for edge in sitemap["edges"]:
            from_name = screen_lookup.get(edge["from_screen_id"], edge["from_screen_id"])
            to_name = screen_lookup.get(edge["to_screen_id"], edge["to_screen_id"])
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f"{from_name} → {to_name} ").bold = True
            p.add_run(f"(trigger: {edge['trigger']})").italic = True

    doc.add_paragraph()


def _add_entities(doc: Document, entities: list) -> None:
    _add_heading(doc, "4. Data Entities", level=1)

    for entity in entities:
        sub = doc.add_paragraph()
        sub_run = sub.add_run(entity["name"].capitalize())
        sub_run.bold = True
        sub_run.font.size = Pt(12)
        sub_run.font.color.rgb = GOLD

        table = doc.add_table(rows=1, cols=3)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.autofit = False
        widths = [Inches(2.0), Inches(1.5), Inches(1.5)]
        headers = ["Field", "Type", "Required"]

        for i, cell in enumerate(table.rows[0].cells):
            cell.width = widths[i]
            _set_cell_text(cell, headers[i], bold=True, color=NAVY, size=9)
            _set_cell_background(cell, LIGHT_GOLD_BG)

        for attr in entity["attributes"]:
            row = table.add_row().cells
            for i, w in enumerate(widths):
                row[i].width = w
            _set_cell_text(row[0], attr["name"], size=9)
            _set_cell_text(row[1], attr["type"], size=9)
            _set_cell_text(row[2], "Yes" if attr["required"] else "No", size=9)

        if entity["relationships"]:
            rel_p = doc.add_paragraph()
            rel_p.add_run("Relationships: ").bold = True
            rel_text = ", ".join(f"{r['relationship_type']} → {r['to_entity']}" for r in entity["relationships"])
            rel_p.add_run(rel_text)

        doc.add_paragraph()


def _add_tech_stack(doc: Document, stack: dict) -> None:
    _add_heading(doc, "5. Recommended Technology Stack", level=1)

    table = doc.add_table(rows=5, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    widths = [Inches(2.0), Inches(4.2)]

    rows = [
        ("Framework", stack["framework"]),
        ("State Management", stack["state_management"]),
        ("UI Library", stack["ui_library"]),
        ("Navigation", stack["navigation_library"]),
        ("Backend Service", stack["backend_service"]),
    ]
    for i, (label, value) in enumerate(rows):
        cells = table.rows[i].cells
        cells[0].width, cells[1].width = widths
        _set_cell_text(cells[0], label, bold=True, color=WHITE, size=10)
        _set_cell_background(cells[0], LIGHT_NAVY_BG)
        _set_cell_text(cells[1], value, size=10)

    if stack.get("reasoning"):
        doc.add_paragraph()
        reasoning_heading = doc.add_paragraph()
        reasoning_run = reasoning_heading.add_run("Reasoning")
        reasoning_run.bold = True
        reasoning_run.font.color.rgb = NAVY

        for reason in stack["reasoning"]:
            doc.add_paragraph(reason, style="List Bullet")

    doc.add_paragraph()


def _add_footer_timing(doc: Document, srs: dict) -> None:
    _add_heading(doc, "6. Generation Metadata", level=1)
    table = doc.add_table(rows=len(srs["stage_timings"]) + 1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    widths = [Inches(3.0), Inches(3.2)]

    _set_cell_text(table.rows[0].cells[0], "Pipeline Stage", bold=True, color=WHITE, size=10)
    _set_cell_text(table.rows[0].cells[1], "Duration (ms)", bold=True, color=WHITE, size=10)
    for cell in table.rows[0].cells:
        _set_cell_background(cell, LIGHT_NAVY_BG)
    table.rows[0].cells[0].width, table.rows[0].cells[1].width = widths

    for i, timing in enumerate(srs["stage_timings"], start=1):
        cells = table.rows[i].cells
        cells[0].width, cells[1].width = widths
        _set_cell_text(cells[0], timing["stage_name"].replace("_", " ").title(), size=9)
        _set_cell_text(cells[1], f"{timing['duration_ms']:.2f}", size=9)

    doc.add_paragraph()
    total_p = doc.add_paragraph()
    total_p.add_run(f"Total generation time: {srs['total_duration_ms']:.2f} ms").bold = True


def generate_srs_document(json_path: str, output_path: str) -> None:
    with open(json_path, "r", encoding="utf-8") as f:
        srs = json.load(f)

    doc = Document()

    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    generated_at = srs.get("generated_at", datetime.utcnow().isoformat())
    _add_cover_page(doc, srs["raw_features"]["original_prompt"], generated_at, srs["trace_id"])
    _add_table_of_contents_summary(doc, srs)
    _add_functional_requirements(doc, srs["functional_requirements"]["requirements"])
    _add_non_functional_requirements(doc, srs["non_functional_requirements"]["requirements"])
    _add_sitemap(doc, srs["sitemap"])
    _add_entities(doc, srs["entities"]["entities"])
    _add_tech_stack(doc, srs["tech_stack"])
    _add_footer_timing(doc, srs)

    doc.save(output_path)
    print(f"SRS document saved to {output_path}")

if __name__ == "__main__":
    import glob
    import os

    files = glob.glob("srs_outputs/*.json")

    if not files:
        print("No SRS JSON files found.")
        sys.exit(1)

    input_file = max(files, key=os.path.getmtime)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(
    "srs_outputs",
    f"SRS_Document_{timestamp}.docx"
)

    generate_srs_document(input_file, output_file)