"""Twenty small, inspectable React Native component contracts."""
import json
from pathlib import Path
HEAD="import React from 'react';\nimport {View,Text,Pressable,TextInput,StyleSheet} from 'react-native';\n"
BODIES={
'HeroBanner':("{title='New discoveries',subtitle='Curated for everyday life',primary='#7856d8',onPress}","<View style={{padding:24,borderRadius:24,backgroundColor:primary}}><Text style={{fontSize:30,fontWeight:'800',color:'white'}}>{title}</Text><Text style={{color:'white',marginVertical:14}}>{subtitle}</Text><Pressable accessibilityRole='button' onPress={onPress}><Text style={{color:'white',fontWeight:'700'}}>Explore collection →</Text></Pressable></View>"),
'CategoryChip':("{label='Essentials',selected=false,onPress,primary='#7856d8'}","<Pressable accessibilityRole='button' accessibilityState={{selected}} onPress={onPress} style={{padding:12,borderRadius:30,backgroundColor:selected?primary:'#eee9f5'}}><Text style={{color:selected?'white':'#483a60'}}>{label}</Text></Pressable>"),
'SearchBar':("{value='',onChangeText,placeholder='Search products'}","<TextInput accessibilityLabel={placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} style={{padding:14,borderWidth:1,borderColor:'#ddd4e8',borderRadius:14,color:'#302338'}}/>"),
'CartItem':("{name='Selected item',price=1990,quantity=1,onIncrease,onDecrease}","<View style={{padding:16,borderBottomWidth:1,borderColor:'#eee'}}><Text style={{fontWeight:'700'}}>{name}</Text><Text>Rs. {price*quantity}</Text><View style={{flexDirection:'row',gap:18,alignItems:'center',marginTop:12}}><Pressable accessibilityRole='button' accessibilityLabel='Decrease quantity' onPress={onDecrease}><Text style={{fontSize:24}}>−</Text></Pressable><Text>{quantity}</Text><Pressable accessibilityRole='button' accessibilityLabel='Increase quantity' onPress={onIncrease}><Text style={{fontSize:24}}>+</Text></Pressable></View></View>"),
'CheckoutButton':("{label='Continue to checkout',onPress,disabled=false,primary='#7856d8'}","<Pressable accessibilityRole='button' accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={{padding:16,borderRadius:14,backgroundColor:primary,opacity:disabled?.5:1}}><Text style={{textAlign:'center',color:'white',fontWeight:'700'}}>{label}</Text></Pressable>"),
'PriceTag':("{amount=1990,currency='Rs.',originalPrice}","<View style={{flexDirection:'row',gap:8}}><Text style={{fontSize:20,fontWeight:'700'}}>{currency} {amount.toLocaleString()}</Text>{originalPrice>amount&&<Text style={{textDecorationLine:'line-through',color:'#888'}}>{currency} {originalPrice.toLocaleString()}</Text>}</View>"),
'DiscountBadge':("{percent=20}","<View style={{backgroundColor:'#fce9e2',padding:7,borderRadius:9,alignSelf:'flex-start'}}><Text style={{color:'#a95438',fontWeight:'700'}}>{Math.max(0,Math.min(100,percent))}% OFF</Text></View>"),
'RatingStars':("{rating=4,count=12}","<View accessibilityLabel={rating+' out of 5 stars, '+count+' reviews'} style={{flexDirection:'row',gap:6}}><Text style={{color:'#be9344'}}>{'★'.repeat(Math.max(0,Math.min(5,Math.round(rating))))}{'☆'.repeat(5-Math.max(0,Math.min(5,Math.round(rating))))}</Text><Text style={{color:'#888'}}>({count})</Text></View>"),
'SectionHeading':("{title='The collection',actionLabel='See all',onAction,color='#302338'}","<View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:18}}><Text style={{fontSize:24,fontWeight:'700',color}}>{title}</Text>{onAction&&<Pressable accessibilityRole='button' onPress={onAction}><Text style={{color:'#7856d8'}}>{actionLabel}</Text></Pressable>}</View>"),
'EmptyState':("{title='Nothing here yet',message='Try another search',onReset}","<View style={{padding:30,alignItems:'center',gap:12}}><Text style={{fontSize:36}}>◇</Text><Text style={{fontWeight:'700',fontSize:20}}>{title}</Text><Text style={{color:'#888'}}>{message}</Text>{onReset&&<Pressable accessibilityRole='button' onPress={onReset}><Text style={{color:'#7856d8'}}>Reset</Text></Pressable>}</View>"),
'ContactCard':("{email='hello@example.com',phone='+92 300 0000000',address='Islamabad, Pakistan'}","<View style={{padding:22,borderRadius:20,backgroundColor:'#f4eefb',gap:12}}><Text style={{fontSize:23,fontWeight:'700'}}>Get in touch</Text><Text selectable>{email}</Text><Text selectable>{phone}</Text><Text>{address}</Text></View>"),
'AboutCard':("{name='Our story',description='Thoughtful essentials, made for everyday life.'}","<View style={{padding:24,gap:16}}><Text style={{fontSize:28,fontWeight:'700'}}>{name}</Text><Text style={{fontSize:16,lineHeight:25,color:'#746580'}}>{description}</Text></View>"),
'QuantityControl':("{value=1,onChange,min=0,max=99}","<View style={{flexDirection:'row',alignItems:'center',gap:18}}><Pressable accessibilityRole='button' accessibilityLabel='Decrease quantity' disabled={value<=min} onPress={()=>onChange?.(Math.max(min,value-1))}><Text style={{fontSize:24}}>−</Text></Pressable><Text>{value}</Text><Pressable accessibilityRole='button' accessibilityLabel='Increase quantity' disabled={value>=max} onPress={()=>onChange?.(Math.min(max,value+1))}><Text style={{fontSize:24}}>+</Text></Pressable></View>"),
'OrderSummary':("{subtotal=0,delivery=0}","<View style={{padding:20,borderRadius:16,backgroundColor:'#f4eefb',gap:12}}><Text>Subtotal: Rs. {subtotal.toLocaleString()}</Text><Text>Delivery: Rs. {delivery.toLocaleString()}</Text><Text style={{fontWeight:'800',fontSize:20}}>Total: Rs. {(subtotal+delivery).toLocaleString()}</Text></View>"),
'AddressField':("{value='',onChangeText,error=''}","<View><TextInput accessibilityLabel='Delivery address' value={value} onChangeText={onChangeText} placeholder='Delivery address' multiline style={{padding:14,borderWidth:1,borderColor:error?'#be6755':'#ddd4e8',borderRadius:12}}/>{error!==''&&<Text accessibilityRole='alert' style={{color:'#be6755',marginTop:5}}>{error}</Text>}</View>"),
'NavigationTab':("{label='Home',active=false,onPress,primary='#7856d8'}","<Pressable accessibilityRole='tab' accessibilityState={{selected:active}} onPress={onPress} style={{padding:14,borderRadius:12,backgroundColor:active?primary+'20':'transparent'}}><Text style={{color:active?primary:'#8a7c98',fontWeight:'600'}}>{label}</Text></Pressable>"),
'StockBadge':("{stock=5}","<Text style={{color:stock>0?'#518365':'#b75f4c',fontSize:12}}>{stock>0?stock+' in stock':'Out of stock'}</Text>"),
'ServiceCard':("{title='Signature service',duration=30,price=1500,onBook}","<View style={{padding:20,borderRadius:18,borderWidth:1,borderColor:'#e5deed',gap:10}}><Text style={{fontSize:20,fontWeight:'700'}}>{title}</Text><Text>{duration} minutes · Rs. {price}</Text><Pressable accessibilityRole='button' onPress={onBook} style={{padding:13,backgroundColor:'#7856d8',borderRadius:12}}><Text style={{color:'white',textAlign:'center'}}>Book service</Text></Pressable></View>"),
'Divider':("{color='#e4dce9',spacing=16}","<View style={{height:1,backgroundColor:color,marginVertical:spacing}}/>"),
}
def component_source(name):
    if name=='ProductCard':return (Path(__file__).parent/'templates/ProductCard.jsx').read_text()
    props,body=BODIES[name]
    return HEAD+f'export default function {name}({props}) {{ return {body}; }}\n'
