"""
backend/utilities/code_editor/tests/test_code_editor.py
========================================================
All tests for CodeEditor — unit tests AND the pipeline
boundary test (CodeEditor → MdConverter contract) live here.

No separate integration folder.

Run:
    cd jinie
    python -m pytest backend/utilities/code_editor/tests/ -v
"""

import os
import sys
import pytest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from backend.utilities.file_handler.file_handler          import FileHandler
from backend.utilities.file_handler.file_handler_contract import FilePayload
from backend.utilities.code_editor.code_editor          import CodeEditor
from backend.utilities.code_editor.code_editor_contract import (
    CodePayload, EditReceipt, CodeEditorError,
)


# ═══════════════════════════════════════════════════════════════
# FIXTURES
# ═══════════════════════════════════════════════════════════════

@pytest.fixture
def fh():
    return FileHandler()


@pytest.fixture
def ce():
    return CodeEditor()


@pytest.fixture
def dart_file(tmp_path):
    """
    Dart file with Jinie placeholder tokens —
    exactly what CodeT5 (Compiler / Module 06) generates.
    CodeEditor's job is to fill these placeholders.
    """
    content = (
        "import 'package:flutter/material.dart';\n"
        "\n"
        "// TODO: fill placeholders before export\n"
        "class __WIDGET_NAME__ extends StatelessWidget {\n"
        "  final String title;\n"
        "  final double price;\n"
        "\n"
        "  const __WIDGET_NAME__("
        "{required this.title, required this.price});\n"
        "\n"
        "  @override\n"
        "  Widget build(BuildContext context) {\n"
        "    return Card(\n"
        "      color: __PRIMARY_COLOR__,\n"
        "      child: Text('__CURRENCY__ - ' + title),\n"
        "    );\n"
        "  }\n"
        "}\n"
    )
    path = tmp_path / "product_card.dart"
    path.write_text(content, encoding="utf-8")
    return str(path), content


@pytest.fixture
def loaded_ce(fh, dart_file):
    """CodeEditor already loaded with the dart_file fixture."""
    path, _ = dart_file
    ce = CodeEditor()
    ce.load_file(fh.read(path))
    return ce


# ═══════════════════════════════════════════════════════════════
# 1. LOAD FILE
# ═══════════════════════════════════════════════════════════════

class TestLoadFile:

    def test_raises_type_error_for_raw_string(self, ce):
        with pytest.raises(TypeError):
            ce.load_file("class ProductCard {}")

    def test_raises_type_error_for_none(self, ce):
        with pytest.raises(TypeError):
            ce.load_file(None)  # type: ignore

    def test_accepts_file_payload(self, fh, ce, dart_file):
        path, _ = dart_file
        ce.load_file(fh.read(path))   # must not raise
        assert ce.line_count > 0

    def test_returns_self_for_fluent_api(self, fh, ce, dart_file):
        path, _ = dart_file
        result = ce.load_file(fh.read(path))
        assert result is ce

    def test_sets_line_count_correctly(self, fh, ce, dart_file):
        path, content = dart_file
        ce.load_file(fh.read(path))
        assert ce.line_count == len(content.splitlines())

    def test_reload_clears_edit_history(self, fh, dart_file):
        path, _ = dart_file
        ce = CodeEditor()
        ce.load_file(fh.read(path))
        ce.insert_lines(0, ["// header"])
        ce.load_file(fh.read(path))        # reload
        assert ce.get_payload().edit_history == []

    def test_last_receipt_is_none_after_load(self, fh, ce, dart_file):
        path, _ = dart_file
        ce.load_file(fh.read(path))
        assert ce.last_receipt is None


# ═══════════════════════════════════════════════════════════════
# 2. INSERT LINES
# ═══════════════════════════════════════════════════════════════

class TestInsertLines:

    def test_prepend_at_zero_inserts_before_line_1(self, loaded_ce):
        """Compiler adds Jinie header at very top of Dart file."""
        first_before = loaded_ce.preview(1, 1)
        loaded_ce.insert_lines(0, ["// Generated by Jinie — do not edit"])
        assert loaded_ce.preview(1, 1) == "// Generated by Jinie — do not edit"
        assert loaded_ce.preview(2, 2) == first_before

    def test_insert_at_end_appends(self, loaded_ce):
        old_count = loaded_ce.line_count
        loaded_ce.insert_lines(old_count, ["// end of file"])
        assert loaded_ce.line_count == old_count + 1
        assert loaded_ce.preview(loaded_ce.line_count) == "// end of file"

    def test_insert_multiple_import_lines(self, loaded_ce):
        """Compiler inserts several import lines at top."""
        old_count = loaded_ce.line_count
        imports = [
            "import 'package:provider/provider.dart';",
            "import 'package:jinie_store/models/product.dart';",
        ]
        loaded_ce.insert_lines(0, imports)
        assert loaded_ce.line_count == old_count + 2
        assert loaded_ce.preview(1, 1) == imports[0]
        assert loaded_ce.preview(2, 2) == imports[1]

    def test_out_of_range_raises_error(self, loaded_ce):
        with pytest.raises(CodeEditorError) as exc:
            loaded_ce.insert_lines(9999, ["oops"])
        assert exc.value.code == "LINE_OUT_OF_RANGE"

    def test_without_load_raises_no_file_loaded(self, ce):
        with pytest.raises(CodeEditorError) as exc:
            ce.insert_lines(0, ["x"])
        assert exc.value.code == "NO_FILE_LOADED"

    def test_returns_self_for_chaining(self, loaded_ce):
        assert loaded_ce.insert_lines(0, ["// h"]) is loaded_ce

    def test_last_receipt_operation_is_insert(self, loaded_ce):
        loaded_ce.insert_lines(0, ["// h"])
        assert loaded_ce.last_receipt.operation == "INSERT"

    def test_last_receipt_snapshot_line_count(self, loaded_ce):
        old_count = loaded_ce.line_count
        loaded_ce.insert_lines(0, ["// h"])
        assert loaded_ce.last_receipt.snapshot_line_count == old_count + 1


# ═══════════════════════════════════════════════════════════════
# 3. DELETE LINES
# ═══════════════════════════════════════════════════════════════

class TestDeleteLines:

    def test_delete_removes_todo_comment(self, loaded_ce):
        """
        Dart file line 3 is the TODO comment.
        Compiler removes it after filling all placeholders.
        """
        assert "TODO" in loaded_ce.preview(3, 3)
        before = loaded_ce.line_count
        loaded_ce.delete_lines(3, 3)
        assert loaded_ce.line_count == before - 1
        assert "TODO" not in loaded_ce.preview(3, 3)

    def test_delete_multiple_lines(self, loaded_ce):
        before = loaded_ce.line_count
        loaded_ce.delete_lines(1, 3)
        assert loaded_ce.line_count == before - 3

    def test_out_of_range_raises_error(self, loaded_ce):
        with pytest.raises(CodeEditorError) as exc:
            loaded_ce.delete_lines(1, 9999)
        assert exc.value.code == "LINE_OUT_OF_RANGE"

    def test_without_load_raises_no_file_loaded(self, ce):
        with pytest.raises(CodeEditorError) as exc:
            ce.delete_lines(1, 1)
        assert exc.value.code == "NO_FILE_LOADED"

    def test_returns_self_for_chaining(self, loaded_ce):
        assert loaded_ce.delete_lines(1, 1) is loaded_ce

    def test_last_receipt_operation_is_delete(self, loaded_ce):
        loaded_ce.delete_lines(1, 1)
        assert loaded_ce.last_receipt.operation == "DELETE"


# ═══════════════════════════════════════════════════════════════
# 4. REPLACE TOKEN  (core Jinie use case)
# ═══════════════════════════════════════════════════════════════

class TestReplaceToken:

    def test_replace_widget_name_placeholder(self, loaded_ce):
        """
        __WIDGET_NAME__ appears twice (class def + constructor).
        Both must be replaced.
        """
        loaded_ce.replace_token("__WIDGET_NAME__", "ProductCard")
        text = loaded_ce.preview()
        assert "ProductCard"      in text
        assert "__WIDGET_NAME__"  not in text
        assert loaded_ce.last_receipt.replacements == 2

    def test_replace_primary_color_placeholder(self, loaded_ce):
        loaded_ce.replace_token("__PRIMARY_COLOR__", "Color(0xFF1A73E8)")
        assert "Color(0xFF1A73E8)"  in loaded_ce.preview()
        assert "__PRIMARY_COLOR__"  not in loaded_ce.preview()

    def test_replace_currency_placeholder(self, loaded_ce):
        loaded_ce.replace_token("__CURRENCY__", "PKR")
        assert "PKR"          in loaded_ce.preview()
        assert "__CURRENCY__" not in loaded_ce.preview()

    def test_replace_all_placeholders_in_chain(self, fh, tmp_path):
        """Full Compiler chain — all three placeholders replaced."""
        content = (
            "class __WIDGET_NAME__ {\n"
            "  Color c = __PRIMARY_COLOR__;\n"
            "  String cur = '__CURRENCY__';\n"
            "}\n"
        )
        path = str(tmp_path / "w.dart")
        Path(path).write_text(content, encoding="utf-8")

        text = (
            CodeEditor()
            .load_file(fh.read(path))
            .replace_token("__WIDGET_NAME__",  "CartItem")
            .replace_token("__PRIMARY_COLOR__","Color(0xFF000000)")
            .replace_token("__CURRENCY__",     "PKR")
            .get_payload()
            .edited_content
        )

        assert "CartItem"           in text
        assert "Color(0xFF000000)"  in text
        assert "PKR"                in text
        assert "__WIDGET_NAME__"    not in text
        assert "__PRIMARY_COLOR__"  not in text
        assert "__CURRENCY__"       not in text

    def test_replace_specific_occurrence_only(self, fh, tmp_path):
        content = "foo foo foo"
        path = str(tmp_path / "t.txt")
        Path(path).write_text(content, encoding="utf-8")
        ce = CodeEditor()
        ce.load_file(fh.read(path))
        ce.replace_token("foo", "bar", occurrence=2)
        assert ce.preview() == "foo bar foo"

    def test_token_not_found_raises(self, loaded_ce):
        with pytest.raises(CodeEditorError) as exc:
            loaded_ce.replace_token("__DOES_NOT_EXIST__", "x")
        assert exc.value.code == "TOKEN_NOT_FOUND"

    def test_nth_occurrence_out_of_range_raises(self, fh, tmp_path):
        path = str(tmp_path / "t.txt")
        Path(path).write_text("a a", encoding="utf-8")
        ce = CodeEditor()
        ce.load_file(fh.read(path))
        with pytest.raises(CodeEditorError) as exc:
            ce.replace_token("a", "b", occurrence=99)
        assert exc.value.code == "TOKEN_NOT_FOUND"

    def test_without_load_raises_no_file_loaded(self, ce):
        with pytest.raises(CodeEditorError) as exc:
            ce.replace_token("x", "y")
        assert exc.value.code == "NO_FILE_LOADED"

    def test_returns_self_for_chaining(self, loaded_ce):
        assert loaded_ce.replace_token("__WIDGET_NAME__", "X") is loaded_ce


# ═══════════════════════════════════════════════════════════════
# 5. REPLACE BLOCK
# ═══════════════════════════════════════════════════════════════

class TestReplaceBlock:

    def test_replaces_first_line(self, loaded_ce):
        loaded_ce.replace_block(1, 1, "// replaced import")
        assert loaded_ce.preview(1, 1) == "// replaced import"

    def test_one_line_replaced_with_three_expands_file(self, loaded_ce):
        before = loaded_ce.line_count
        loaded_ce.replace_block(1, 1, "// A\n// B\n// C")
        assert loaded_ce.line_count == before + 2

    def test_returns_self_for_chaining(self, loaded_ce):
        assert loaded_ce.replace_block(1, 1, "// x") is loaded_ce

    def test_out_of_range_raises_error(self, loaded_ce):
        with pytest.raises(CodeEditorError) as exc:
            loaded_ce.replace_block(1, 9999, "x")
        assert exc.value.code == "LINE_OUT_OF_RANGE"

    def test_last_receipt_operation_is_replace_block(self, loaded_ce):
        loaded_ce.replace_block(1, 1, "// x")
        assert loaded_ce.last_receipt.operation == "REPLACE_BLOCK"


# ═══════════════════════════════════════════════════════════════
# 6. GET PAYLOAD
# ═══════════════════════════════════════════════════════════════

class TestGetPayload:

    def test_returns_code_payload_type(self, loaded_ce):
        assert isinstance(loaded_ce.get_payload(), CodePayload)

    def test_language_is_dart_for_dart_file(self, loaded_ce):
        assert loaded_ce.get_payload().language == "dart"

    def test_language_is_python_for_py_file(self, fh, tmp_path):
        path = str(tmp_path / "utils.py")
        Path(path).write_text("def greet(): pass\n", encoding="utf-8")
        cp = CodeEditor().load_file(fh.read(path)).get_payload()
        assert cp.language == "python"

    def test_language_is_yaml_for_pubspec(self, fh, tmp_path):
        path = str(tmp_path / "pubspec.yaml")
        Path(path).write_text("name: jinie_store\n", encoding="utf-8")
        cp = CodeEditor().load_file(fh.read(path)).get_payload()
        assert cp.language == "yaml"

    def test_edited_content_reflects_all_replacements(self, loaded_ce):
        loaded_ce.replace_token("__WIDGET_NAME__",  "ProductCard")
        loaded_ce.replace_token("__PRIMARY_COLOR__","Color(0xFF1A73E8)")
        loaded_ce.replace_token("__CURRENCY__",     "PKR")
        cp = loaded_ce.get_payload()
        assert "ProductCard"        in cp.edited_content
        assert "Color(0xFF1A73E8)"  in cp.edited_content
        assert "PKR"                in cp.edited_content
        assert "__WIDGET_NAME__"    not in cp.edited_content

    def test_original_content_always_unchanged(self, fh, dart_file):
        path, original = dart_file
        ce = CodeEditor()
        ce.load_file(fh.read(path))
        ce.replace_token("__WIDGET_NAME__", "ProductCard")
        cp = ce.get_payload()
        assert "__WIDGET_NAME__" in cp.original_content   # original kept
        assert "ProductCard"     in cp.edited_content     # edit applied

    def test_trace_id_prefixed_CE(self, loaded_ce):
        assert loaded_ce.get_payload().trace_id.startswith("CE-")

    def test_source_trace_id_links_back_to_file_payload(self, fh, dart_file):
        path, _ = dart_file
        fp = fh.read(path)
        cp = CodeEditor().load_file(fp).get_payload()
        assert cp.source_trace_id == fp.trace_id

    def test_edit_history_captures_ops_in_order(self, loaded_ce):
        loaded_ce.insert_lines(0, ["// header"])
        loaded_ce.replace_token("__WIDGET_NAME__", "ProductCard")
        loaded_ce.delete_lines(1, 1)
        ops = [r.operation for r in loaded_ce.get_payload().edit_history]
        assert ops == ["INSERT", "REPLACE_TOKEN", "DELETE"]

    def test_get_payload_is_idempotent(self, loaded_ce):
        p1 = loaded_ce.get_payload()
        p2 = loaded_ce.get_payload()
        assert p1.edited_content == p2.edited_content
        assert p1.trace_id       == p2.trace_id

    def test_before_load_raises_no_file_loaded(self, ce):
        with pytest.raises(CodeEditorError) as exc:
            ce.get_payload()
        assert exc.value.code == "NO_FILE_LOADED"

    def test_source_path_is_absolute(self, loaded_ce):
        assert os.path.isabs(loaded_ce.get_payload().source_path)

    def test_extension_is_dart(self, loaded_ce):
        assert loaded_ce.get_payload().extension == ".dart"


# ═══════════════════════════════════════════════════════════════
# 7. DOWNSTREAM CONTRACT — CodePayload ready for MdConverter
#    These tests verify what MdConverter will receive.
#    They live here because CodeEditor owns this contract.
# ═══════════════════════════════════════════════════════════════

class TestMdConverterContract:

    def test_edited_content_is_non_empty_string(self, loaded_ce):
        """MdConverter needs a non-empty string to wrap in a code block."""
        cp = loaded_ce.get_payload()
        assert isinstance(cp.edited_content, str)
        assert len(cp.edited_content) > 0

    def test_language_field_is_dart(self, loaded_ce):
        """MdConverter uses language for ```dart fenced block tag."""
        assert loaded_ce.get_payload().language == "dart"

    def test_source_path_provided_for_attribution(self, loaded_ce):
        """MdConverter adds source_path as attribution in the Markdown."""
        cp = loaded_ce.get_payload()
        assert cp.source_path
        assert os.path.isabs(cp.source_path)

    def test_trace_id_for_traceability_matrix(self, loaded_ce):
        """
        MdConverter chains this CE trace_id into Module 03
        (Traceability Manager) so every Markdown block is traceable.
        """
        assert loaded_ce.get_payload().trace_id.startswith("CE-")

    def test_fluent_chain_and_step_by_step_produce_same_output(
            self, fh, tmp_path):
        """
        Fluent API and step-by-step must give identical CodePayloads.
        MdConverter must receive the same content either way.
        """
        content = "class __WIDGET_NAME__ {}\n"
        path    = str(tmp_path / "w.dart")
        Path(path).write_text(content, encoding="utf-8")

        # fluent
        cp_fluent = (
            CodeEditor()
            .load_file(fh.read(path))
            .replace_token("__WIDGET_NAME__", "ProductCard")
            .get_payload()
        )

        # step-by-step
        ce = CodeEditor()
        ce.load_file(fh.read(path))
        ce.replace_token("__WIDGET_NAME__", "ProductCard")
        cp_step = ce.get_payload()

        assert cp_fluent.edited_content == cp_step.edited_content
        assert cp_fluent.language       == cp_step.language
        assert cp_fluent.extension      == cp_step.extension