import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(new URL('../frontend/package.json',import.meta.url));
const {chromium}=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'):require('playwright');
const api=spawn(process.env.PYTHON||'python',['-m','uvicorn','main:app','--host','127.0.0.1','--port','8011'],{cwd:path.join(root,'backend'),env:{...process.env,JINIE_ALLOWED_ORIGINS:'http://127.0.0.1:5181',JINIE_DATA_DIR:path.join(root,'runtime-browser-test')},stdio:'pipe'});
const web=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5181'],{cwd:path.join(root,'frontend'),env:{...process.env,VITE_API_URL:'http://127.0.0.1:8011'},stdio:'pipe'});
let logs='';for(const child of [api,web]){child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);}
let browser;
try{
 for(let i=0;i<100;i++){try{await fetch('http://127.0.0.1:5181');await fetch('http://127.0.0.1:8011/api/health');break;}catch{await new Promise(r=>setTimeout(r,200));}}
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']}: {})});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5181');await page.getByText('Engine connected').waitFor();
 fs.mkdirSync(path.join(root,'docs/screenshots'),{recursive:true});
 await page.screenshot({path:path.join(root,'docs/screenshots/01-overview.png'),fullPage:true});
 await page.getByRole('button',{name:'Create my app'}).click();
 await page.getByRole('heading',{name:'A clear brief. A better build.'}).waitFor();
 await page.getByRole('button',{name:'Approve all reviewed requirements'}).click();
 await page.getByRole('button',{name:'Design direction'}).click();
 await page.getByRole('button',{name:'Generate app'}).click();
 await page.getByRole('link',{name:'Download project'}).waitFor({timeout:60000});
 const projectId=await page.evaluate(()=>localStorage.getItem('jinie_project_id'));
 const built=await (await fetch('http://127.0.0.1:8011/api/projects/'+projectId)).json();
 if(!built.components.some(c=>c.name==='ProductCard'&&c.source==='CodeT5 candidate'))throw new Error('Expected actual CodeT5 component, got fallback');

 const frame=page.frameLocator('iframe[title="Generated React Native app"]');
 await frame.getByText('The Everyday Edit',{exact:true}).waitFor({timeout:15000});
 await frame.getByRole('button',{name:'Add Everyday linen shirt to bag'}).click();
 await frame.getByRole('button',{name:'Bag · 1'}).click();
 await frame.getByRole('button',{name:'Continue to checkout'}).click();
 await frame.getByRole('button',{name:'Place demo order'}).click();
 await frame.getByText('Enter your name and a delivery address of at least 8 characters.').waitFor();
 await frame.getByLabel('Full name',{exact:true}).fill('Ali Sher');
 await frame.getByLabel('Delivery address',{exact:true}).fill('Test delivery address Islamabad');
 await frame.getByRole('button',{name:'Place demo order'}).click();
 await frame.getByText('Demo order saved on this device. No payment was charged.').waitFor();
 await frame.getByRole('button',{name:'search',exact:true}).click();
 await frame.getByLabel('Search products',{exact:true}).fill('zzzz-no-match');
 await frame.getByText('No products match your search.').waitFor();
 await frame.getByRole('button',{name:'home',exact:true}).click();
 await frame.getByLabel('Search products',{exact:true}).fill('');
 await page.screenshot({path:path.join(root,'docs/screenshots/02-preview.png'),fullPage:true});
 await page.getByLabel('Preview component').selectOption('QuantityControl');
 await frame.getByText('ISOLATED COMPONENT PREVIEW').waitFor();
 await frame.getByRole('button',{name:'Increase quantity'}).click();
 await frame.getByText('2',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Evidence',exact:true}).click();
 await page.getByText('React Native Web source bundles successfully').waitFor();
 await page.screenshot({path:path.join(root,'docs/screenshots/03-evidence.png'),fullPage:true});
 await page.getByRole('button',{name:'Code',exact:true}).click();
 await page.getByRole('button',{name:/config\.json/}).click();
 const editor=page.locator('#source-code');await editor.waitFor();
 const oldConfig=JSON.parse(await editor.inputValue());oldConfig.name='Edited in Jinie';oldConfig.navigation='sidebar';
 await editor.fill(JSON.stringify(oldConfig,null,2));
 await page.getByRole('button',{name:'Save file',exact:true}).click();
 await page.getByRole('button',{name:'Rebuild source'}).click();
 await page.getByRole('link',{name:'Download project'}).waitFor({timeout:60000});
 await page.getByLabel('Preview component').selectOption('');
 await frame.getByText('Edited in Jinie',{exact:true}).waitFor();
 await frame.getByRole('button',{name:'search',exact:true}).click();
 await frame.getByLabel('Search products',{exact:true}).fill('linen');
 await frame.getByRole('button',{name:'Add Everyday linen shirt to bag'}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.screenshot({path:path.join(root,'docs/screenshots/04-mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
 if(overflow)throw new Error('Mobile viewport overflows horizontally');
 if(errors.length)throw new Error('Browser errors: '+errors.join('\n'));
 const report={passed:true,checks:['actual CodeT5 ProductCard accepted','workspace creation','requirement approvals','design generation','actual compiled iframe renders','add to cart','checkout validation','demo order','search empty state','isolated component interaction','evidence display','mobile width','source editor save/rebuild','edited config appears in preview','sidebar navigation'],native_device_tested:false};
 fs.writeFileSync(path.join(root,'docs/browser-test-results.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}catch(e){console.error(logs.slice(-6000));throw e;}finally{await browser?.close();api.kill();web.kill();}
